language: bash

services:
  - docker

cache:
  directories:
    - ./npm

script:
  - docker run --rm -t -v $PWD:/app -w /app -e CI_NODE_INDEX=$CI_NODE_INDEX -e CI_NODE_TOTAL=$CI_NODE_TOTAL -e npm_config_cache=/app/.npm cypress/base:12 bash -c "npm install --only prod && cd test && npm ci && npm run test-ci"

jobs:
  include:
    - env:
      - CI_NODE_INDEX=1
      - CI_NODE_TOTAL=2
    - env:
      - CI_NODE_INDEX=2
      - CI_NODE_TOTAL=2
