language: bash

services:
  - docker

cache:
  directories:
    - ./npm

script:
  - docker run --rm -t -v $PWD:/app -w /app -e npm_config_cache=/app/.npm cypress/base:10 bash -c "npm ci && cd test && npm ci && npm run test"
